import { useEffect, useState } from 'react'
import { ArrowLeft, CheckCircle2, Clock3 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { orderApi } from '../../api/order'
import { paymentApi } from '../../api/payment'
import type { Order } from '../../mocks/types'
import { useToast } from '../../hooks/useToast'
import './MobileCommerce.css'

export default function MobilePayment() { const navigate = useNavigate(); const [params] = useSearchParams(); const { addToast } = useToast(); const [order, setOrder] = useState<Order | null>(null); const [paying, setPaying] = useState(false); const [error, setError] = useState(false); const orderId = params.get('orderId'); const method = params.get('method') === 'alipay' ? '支付宝' : '微信支付'; useEffect(() => { if (!orderId) { setError(true); return } orderApi.get(orderId).then(setOrder).catch(() => setError(true)) }, [orderId]); const pay = async () => { if (!orderId) return; setPaying(true); try { await paymentApi.pay(orderId, method === '支付宝' ? 'alipay' : 'wechat'); navigate(`/m/order-success?orderId=${orderId}`) } catch (err) { addToast(err instanceof Error ? err.message : '支付失败，请稍后重试', 'error') } finally { setPaying(false) } }; if (error) return <div className="mobile-commerce"><div className="mobile-subpage-bar"><button type="button" onClick={() => navigate('/m/orders')}><ArrowLeft size={18} /></button><strong>收银台</strong><span /></div><div className="mobile-commerce-state"><p>订单不存在或已失效</p><button className="mobile-pay-button" type="button" onClick={() => navigate('/m/orders')}>查看订单</button></div></div>; if (!order) return <div className="mobile-commerce"><div className="mobile-subpage-bar"><button type="button" onClick={() => navigate('/m/orders')}><ArrowLeft size={18} /></button><strong>收银台</strong><span /></div><div className="mobile-commerce-state">订单加载中…</div></div>; return <div className="mobile-commerce mobile-payment-page"><div className="mobile-subpage-bar"><button type="button" onClick={() => navigate(`/m/orders/${order.id}`)}><ArrowLeft size={18} /></button><strong>收银台</strong><span /></div><div className="mobile-payment-icon"><Clock3 size={45} /><h2>待支付</h2><p>请在订单关闭前完成支付</p></div><section className="mobile-checkout-card mobile-payment-order"><span>{order.productName}</span><strong>¥{order.amount}</strong><small>订单号：{order.id}</small></section><section className="mobile-checkout-card mobile-payment-choice"><div><span>支付方式</span><b>{method}</b></div><div><span>订单状态</span><b>{order.status === 'pending_pay' ? '待支付' : '已支付'}</b></div></section><button className="mobile-pay-button mobile-payment-submit" disabled={paying || order.status !== 'pending_pay'} type="button" onClick={pay}>{paying ? '支付处理中…' : order.status === 'pending_pay' ? `立即支付 ¥${order.amount}` : '订单已支付'}</button><p className="mobile-payment-tip"><CheckCircle2 size={13} /> 当前为演示支付，接入真实支付需配置支付服务商</p></div> }
